TASK1:
  name: VCR_Q-A
  type: VL-logit
  loss: CrossEntropyLoss
  task_id: 6
  dataroot: data/VCR
  features_h5path1: data/VCR/VCR_resnet101_faster_rcnn_genome.lmdb
  features_h5path2: data/VCR/VCR_gt_resnet101_faster_rcnn_genome.lmdb
  train_annotations_jsonpath: data/VCR/train.jsonl
  val_annotations_jsonpath: data/VCR/val.jsonl
  max_seq_length: 60
  max_region_num: 100
  batch_size: 32
  train_split: train
  val_split: val
  lr: 0.00002
  num_epoch: 20
TASK2:
  name: VCR_QA-R
  type: VL-logit
  loss: CrossEntropyLoss
  task_id: 7
  dataroot: data/VCR
  features_h5path1: data/VCR/VCR_resnet101_faster_rcnn_genome.lmdb
  features_h5path2: data/VCR/VCR_gt_resnet101_faster_rcnn_genome.lmdb
  train_annotations_jsonpath: data/VCR/train.jsonl
  val_annotations_jsonpath: data/VCR/val.jsonl
  max_seq_length: 80
  max_region_num: 100
  batch_size: 32
  train_split: train
  val_split: val
  lr: 0.00002
  num_epoch: 20
TASK3:
  name: RetrievalFlickr30k
  type: VL-logit
  loss: CrossEntropyLoss
  task_id: 9
  dataroot: data/flickr30k
  features_h5path1: data/flickr30k/flickr30k_test_resnet101_faster_rcnn_genome.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: data/flickr30k/all_data_final_train_2014.jsonline
  val_annotations_jsonpath: data/flickr30k/all_data_final_test_set0_2014.jsonline
  max_seq_length: 30
  max_region_num: 102
  batch_size: 64
  train_split: train
  val_split: test
  lr: 0.00002
  num_epoch: 30
